# Create a multiple files
---
- hosts: localhost
  tasks:
    - name: Create a multitple files
      file:
        path: "{{ item }}"
        state: touch
      with_items:
        - test01.txt
        - test02.txt

# Create a one files with content
---
- hosts: localhost
  tasks:
    - name: Creating a file with content
      copy:
        dest: "/home/rad7955/Documents/study/ansible/case1/demo.txt"
        content: |
          ashli
          victor
          joe
