name: Scheduled Workflow at 7:30 PM UTC

on:
  schedule:
    - cron: '35 19 * * *'  
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run task at 7:30 PM UTC
        run: echo "This GitHub Action ran at 7:30 PM UTC!"
